### ISSUE TITLE
OG image for home page

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/docs#22]
Current OG image for our home page is the default Docusaurus. 
<img width="666" alt="Screenshot 2023-11-09 at 7 31 35 pm" src="https://github.com/ZenUml/docs/assets/169417/f89287dd-b4b6-4975-bb68-aeda041e79e6">

If we don't have a better option, the first image is a candidate:

![image](https://github.com/ZenUml/docs/assets/169417/0855d00d-58cc-43c7-8a47-ceb7ce567bf2)
Or
![image](https://github.com/ZenUml/docs/assets/169417/6376aea5-c2dc-448f-ab68-bb3f9ebfe923)

**Comment by unimu-cic** [comment]
It's better to have a distinctive design associated with the brand.
