### ISSUE TITLE
Add robot file to block Google Crawler from indexing Web App and Confluence App pages

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/docs#54]
I have added to to docs repo, but it is cross Web App and Confluence App.

It can be a work or some page rule that returns a robot file for to following domains:
1. conf-full.zenuml.com
2. conf-lite.zenuml.com

This will ensure that Google won't index those pages.

Related error: https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Azenuml.com&item_key=CAMYDyAC&hl=en&sharing_key=6cviEaKh3UboBbX2OltGzQ

**Comment by whimet** [comment]
Deployed:
<img width="1695" alt="image" src="https://github.com/ZenUml/docs/assets/44074/4259f20b-576b-4838-a957-951e280ceffa">
